# Generated by Django 6.0.6 on 2026-06-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ClientePromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('usada', 'Usada'), ('vencida', 'Vencida')], default='asignada', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_cliente', to='clientes.cliente')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_promocion', to='promociones.promocion')),
            ],
            options={
                'verbose_name': 'Promoción asignada',
                'verbose_name_plural': 'Promociones asignadas',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
