# Generated by Django 6.0.6 on 2026-06-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('juego', 'Juego'), ('promocion', 'Promoción'), ('consulta', 'Consulta'), ('evento', 'Evento'), ('otro', 'Otro')], default='juego', max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_visita'],
            },
        ),
    ]
