# Generated by Django 6.0.6 on 2026-06-08 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('reclamo', 'Reclamo'), ('queja', 'Queja'), ('sugerencia', 'Sugerencia'), ('problema', 'Problema'), ('otro', 'Otro')], default='consulta', max_length=30)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='pendiente', max_length=30)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
